/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include <stdio.h>
#include <main.h>
#include <led.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// different tasks of the application
// will be scheduled in a round robin fashion
void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);

void init_systick_timer(uint32_t tick_hz);
__attribute__ ((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack);
void init_tasks_stack(void);
void enable_processor_faults(void);
__attribute__((naked)) void switch_sp_to_psp(void);
uint32_t get_psp_value(void);

/*
uint32_t psp_of_tasks[MAX_TASKS] = {T1_STACK_START, T2_STACK_START, T3_STACK_START, T4_STACK_START};
uint32_t task_handlers[MAX_TASKS];
*/

uint8_t current_task = 1;	// current task running on the CPU
// global count
uint32_t g_tick_count = 0;	// gets updated from systick handler for every interrupt

// TCB
typedef struct
{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t  current_state;
	void (*task_handler)(void);		// void the task handler address
}TCB_t;

TCB_t user_tasks[MAX_TASKS];

int main(void)
{
	enable_processor_faults();
	init_scheduler_stack(SCHED_STACK_START);
	// initialize
	/*
	task_handlers[0] = (uint32_t)task1_handler;
	task_handlers[1] = (uint32_t)task2_handler;
	task_handlers[2] = (uint32_t)task3_handler;
	task_handlers[3] = (uint32_t)task4_handler;
	*/
	init_tasks_stack();
	led_init_all();
	init_systick_timer(TICK_HZ);
	switch_sp_to_psp();
	task1_handler();
	for(;;);
}

void idle_task(void) {
	while(1);
}

// green LED
void task1_handler(void){
	while(1){
		led_on(LED_GREEN);
		task_delay(1000); 		// task will get blocked for the next 1000 ticks (1s)
		led_off(LED_GREEN);
		task_delay(1000);
	}
}

// orange
void task2_handler(void){
	while(1){
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);
	}

}

// blue
void task3_handler(void){
	while(1){
		led_on(LED_BLUE);
		task_delay(250);
		led_off(LED_BLUE);
		task_delay(250);
	}

}

// red
void task4_handler(void){
	while(1){
		led_on(LED_RED);
		task_delay(125);
		led_off(LED_RED);
		task_delay(125);
	}
}
void init_systick_timer(uint32_t tick_hz) {
	uint32_t *pSRVR = (uint32_t*) 0xE000E014;				// this is the start of the register
	uint32_t *pSCSR = (uint32_t*) 0xE000E010;
	uint32_t count_value = SYSTICK_TIM_CLK/tick_hz - 1; 		// input clock to sys_tick timer/desired frequency = count or reload value

	// clear the value in SVR
	*pSRVR &= ~(0x00FFFFFFFF);

	// load the value into SVR
	*pSRVR |= count_value;

	// do some settings
	// need to enable TICKINT
	// need to enable CLKSOURCE - clk to systick timer is pulled from the processor clock
	// this is for the systick control and status register
	*pSCSR |= (1 << 1);	// enable systick exception request
	*pSCSR |= (1 << 2);	// enable the clock source

	// enable the thing
	*pSCSR |= (1 << 0);	// start it
}

// don't want prologue or epilogue sequences
__attribute__ ((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack) {
    __asm volatile("MSR MSP,%0": :  "r" (sched_top_of_stack)  :   );
    __asm volatile("BX LR");
}

void init_tasks_stack(void) {

	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;
	user_tasks[4].current_state = TASK_READY_STATE;

	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;

	user_tasks[0].task_handler = idle_task;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;

	uint32_t *pPSP; 	// pointer
	for (int i = 0; i < MAX_TASKS; i ++) {
		pPSP = (uint32_t*) user_tasks[i].psp_value;
		pPSP--;
		*pPSP = DUMMY_XPSR;

		pPSP--; 	// PC
		*pPSP = (uint32_t) user_tasks[i].task_handler;

		pPSP--;		// LR
		*pPSP = 0xFFFFFFFD;

		// initialize the remaining 13 registers with 0
		for (int j = 0; j < 13; j++) {
			pPSP--;
			*pPSP = 0;
		}

		// need to store the value of psp
		user_tasks[i].psp_value = (uint32_t) pPSP;
	}
}

void enable_processor_faults(void) {
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;

	*pSHCSR |= ( 1 << 16); //mem manage
	*pSHCSR |= ( 1 << 17); //bus fault
	*pSHCSR |= ( 1 << 18); //usage fault
}

uint32_t get_psp_value(void) {
	return user_tasks[current_task].psp_value;
}

void save_psp_value(uint32_t current_psp_value){
	user_tasks[current_task].psp_value = current_psp_value;
}

__attribute__ ((naked)) void switch_sp_to_psp(void){
	// want to initialize psp
	// initialize it with TASK1 stack start
	__asm volatile("PUSH {LR}"); 			// need to save the LR in order to go back to main
	__asm volatile("BL get_psp_value"); 	// branch and link - need to come back to that function
											// return value stored in R0
	__asm volatile("MSR PSP,R0");			// initialize PSP
	__asm volatile("POP {LR}");

	// change SP to PSP using CONTROL register
	__asm volatile("MOV R0, #0x02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("BX LR");				// connects us back to main function
}

void schedule(void)
{
	//	pend the pendSV exception
	// literally all we are doing
	uint32_t *pICSR = (uint32_t*)0xE000ED04;
	*pICSR |= ( 1 << 28);

}

void task_delay(uint32_t tick_count) {
	// disable interrupt
	// this will be for a small amount of time - doesn't work for RTOS systems
	INTERRUPT_DISABLE();

	if(current_task)	// only blocking user tasks - if the task == 0, then it's idle task
	{
	   user_tasks[current_task].block_count = g_tick_count + tick_count;	// update block count
	   user_tasks[current_task].current_state = TASK_BLOCKED_STATE;			// then you block the state
	   schedule();	// trigger the pendSV
	}

	// enable interrupt
	// have to be careful - don't want to let handler & thread mode to access global variables at the same time
	INTERRUPT_ENABLE();
}


void update_next_task(void){
	int state = TASK_BLOCKED_STATE;

	for(int i= 0 ; i < (MAX_TASKS) ; i++)	// go through all the tasks
	{
		current_task++;
	    current_task %= MAX_TASKS;	// never crosses 4 - should not go to 5
		state = user_tasks[current_task].current_state;	// get its state using that value
		// if ready - it's schedulable
		// also shouldn't be 0 - that is the idle task
		if( (state == TASK_READY_STATE) && (current_task != 0) )
			break;	// task is in ready state - just leave the function
	}

	if(state != TASK_READY_STATE)	// all the tasks are in blocked state
		current_task = 0;			// thus the current state is in the idle state
}

__attribute__ ((naked)) void PendSV_Handler(void) {	// gotten from the startup file

	// save the context of the current task

	// get current running task PSP's value
	__asm volatile("MRS R0,PSP");
	// store SF2 (R4 to R11) using that PSP
	// ! writes R0 back to itself
	__asm volatile("STMDB R0!, {R4-R11}");  	// store multiple registers
	// save current value of PSP
	__asm volatile("BL get_psp_value");

	// retrieve context of next task
	// decide next task to run
	__asm volatile("BL update_next_task");
	// get its past PSP value
	__asm volatile("BL get_psp_value");
	// retrieve SF2 using PSP
	__asm volatile("LDMIA R0!, {R4-R11}");
	// update PSP and exit
	__asm volatile("MSR PSP,R0");
	// need to return control to main
	__asm volatile("POP {LR}");
	__asm volatile("BX LR");

}

void update_global_tick_count(void)
{
	g_tick_count++;
}

void unblock_tasks(void)
{
	for(int i = 1 ; i < MAX_TASKS ; i++)	// check all the tasks except for the idle state
	{
		if(user_tasks[i].current_state != TASK_READY_STATE)
		{
			if(user_tasks[i].block_count == g_tick_count)	// delay is elapsed - blocking period is over
			{
				user_tasks[i].current_state = TASK_READY_STATE;	// thus have to change the state
			}
		}

	}

}

void SysTick_Handler(void){ // from startup file
	uint32_t *pICSR = (uint32_t*)0xE000ED04;	// address of the interrupt control and state register

    update_global_tick_count();

    unblock_tasks();

    // pend the pendSV exception
    *pICSR |= ( 1 << 28);
}

// fault handlers
void HardFault_Handler(void) {
	printf("Exception : HardFault\n");
	while(1);
}


void MemManage_Handler(void) {
	printf("Exception : MemManage\n");
	while(1);
}

void BusFault_Handler(void) {
	printf("Exception : BusFault\n");
	while(1);
}
